"""Adding patient_visit field in appointments

Revision ID: 196ab5ca4219
Revises: b90947f6dd34
Create Date: 2023-12-14 20:06:57.468432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196ab5ca4219'
down_revision = 'b90947f6dd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_visit', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('patient_visit')

    # ### end Alembic commands ###
