"""Adding UserType

Revision ID: 3ed60d3d4bfb
Revises: f89b71021757
Create Date: 2023-12-14 13:04:19.622866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed60d3d4bfb'
down_revision = 'f89b71021757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Enum('ADMIN', 'PATIENT', 'DOCTOR', name='usertype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
