"""Adding additional fields for appointments

Revision ID: b90947f6dd34
Revises: 85683581de71
Create Date: 2023-12-14 19:48:08.391869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90947f6dd34'
down_revision = '85683581de71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_slot_start', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('time_slot_end', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('time_slot_interval', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_visit', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('doctor_visit')
        batch_op.drop_column('time_slot_interval')
        batch_op.drop_column('time_slot_end')
        batch_op.drop_column('time_slot_start')

    # ### end Alembic commands ###
